# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ThroughTree <- function(x, Node, Feature, Split, Yes, No, Missing) {
    .Call('_fbboost_ThroughTree', PACKAGE = 'fbboost', x, Node, Feature, Split, Yes, No, Missing)
}

